### ISSUE TITLE
Which version of SOFA does this need?

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/SofaPython3#32]
I am trying to compile this plugin using SOFA master (6b53f37fa6) and with SOFA v19.06 but it always gives an error related to DAGNode. 

Which version of SOFA does this need?

**Comment by jnbrunet** [comment]
Normally the latest commit of SOFA master, but sometime SofaPython3 will get some lag of 2 or 3 commits behind as we have to fix breaking changes made in SOFA.

I'll close this issue, if you still have a problem, don't hesitate to reopen the issue, but this time , if possible, with more information on the error you are having
