### ISSUE TITLE
emptyController.py

### ISSUE THREAD

**Issue by Emanuele-n** [sofa-framework/SofaPython3#359]
Hello,
OS: Ubuntu 22.04
When running SofaPython3/examples/emptyController.py , I am not able to detect key pressed, key released and mouse events. The other defaults events are working fine.
Can you please help me?

**Comment by alxbilger** [comment]
According to the [doc on events](https://www.sofa-framework.org/community/doc/programming-with-sofa/api-overview/events-in-sofa/), you may need to press CTRL for the keyboard and mouse events. Did you?

**Comment by Emanuele-n** [comment]
I didn't see that, thanks a lot!
