### ISSUE TITLE
Cannot load SofaPython3

### ISSUE THREAD

**Issue by wj9991** [sofa-framework/SofaPython3#377]
Hi, I recently installed SOFA (v23.06.00) on Windows 11. Unfortunately, I cannot load SofaPython3 in the plugin manager of the runSofa interface, nor in Python (Python 3.11.5/Anaconda/Spyder), nor via the cmd.exe line "runSofa/lSofaPython3". I have already checked all the system variables according to the documentation and read all the discussions on GitHub. However, I have not been able to find a solution to this problem. Implementing a different version of the plugin didn't work either. Do you have any suggestions on how to solve the problem? I look forward to your reply.

**Comment by olivier-roussel** [comment]
Hi, it looks like you are using python from anaconda, so you might be in a conda environment when you run `runSofa`. Could you check if your `%CONDA_PREFIX%` environnement variable is defined and if yes what is its value ?
Could you send your log to have more details on the error ?
Where is located your python executable? I think it is the `where python` command on Windows

**Comment by wj9991** [comment]
Thank you for your quick feedback!

Unfortunately there is no %CONDA_PREFIX% environment variable (or any other Conda related variable).

My Python executable is in this path: C:\Program Files\Anaconda\python.exe; (and C:\Users\jwsch\AppData\Local\Microsoft\WindowsApps\python.exe)

Here is the log:
C:\Windows\System32>runSofa -l SofaPython3
[INFO]    [runSofa] PluginRepository paths = C:/Program Files/SOFA/v23.06.00/bin;C:/Program Files/SOFA/v23.06.00/plugins;C:/Program Files/SOFA/v23.06.00/collections;C:/Program Files/SOFA/v23.06.00/bin
[INFO]    [runSofa] DataRepository paths = C:/Program Files/SOFA/v23.06.00/share/sofa;C:/Program Files/SOFA/v23.06.00/share/sofa/examples;C:/Program Files/SOFA/v23.06.00/share/sofa;C:/Program Files/SOFA/v23.06.00/share/sofa/examples
[INFO]    [runSofa] GuiDataRepository paths = C:/Program Files/SOFA/v23.06.00/share/sofa/gui/runSofa;C:/Program Files/SOFA/v23.06.00/share/sofa/gui/qt;C:/Program Files/SOFA/v23.06.00/share/sofa/gui/qt
[INFO]    [GUIManager] Registered batch as a GUI.
[ERROR]   [PluginManager] Plugin loading failed (C:/Program Files/SOFA/v23.06.00/bin/SofaPython3.dll): Das angegebene Modul wurde nicht gefunden.

[INFO]    [runSofa] Loading automatically plugin list in C:/Program Files/SOFA/v23.06.00/bin/plugin_list.conf
[ERROR]   [PluginManager] Plugin loading failed (C:/Program Files/SOFA/v23.06.00/bin/SofaPython3.dll): Das angegebene Modul wurde nicht gefunden.

[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.ODESolver.Forward.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.ODESolver.Backward.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.ODESolver.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.IO.Mesh.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.IO.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Playback.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SceneUtility.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Topology.Container.Constant.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Topology.Container.Dynamic.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Topology.Container.Grid.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Topology.Container.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Topology.Mapping.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Topology.Utility.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Topology.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Visual.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.LinearSystem.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.LinearSolver.Iterative.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.LinearSolver.Direct.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.LinearSolver.Preconditioner.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.LinearSolver.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Mass.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Diffusion.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Mapping.Linear.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Mapping.NonLinear.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Mapping.MappedMatrix.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Mapping.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.StateContainer.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SolidMechanics.Spring.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SolidMechanics.FEM.Elastic.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SolidMechanics.FEM.HyperElastic.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SolidMechanics.FEM.NonUniform.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SolidMechanics.FEM.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SolidMechanics.TensorMass.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.SolidMechanics.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Constraint.Lagrangian.Model.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Constraint.Lagrangian.Correction.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Constraint.Lagrangian.Solver.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Constraint.Lagrangian.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Constraint.Projective.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Constraint.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.AnimationLoop.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.MechanicalLoad.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.Geometry.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.Detection.Algorithm.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.Detection.Intersection.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.Detection.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.Response.Mapper.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.Response.Contact.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.Response.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Collision.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Setting.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Controller.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Engine.Analyze.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Engine.Generate.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Engine.Select.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Engine.Transform.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Engine.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.Haptics.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.Component.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GL.Component.Rendering2D.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GL.Component.Rendering3D.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GL.Component.Engine.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GL.Component.Shader.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GL.Component.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GUI.Component.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GUI.Batch.dll
[INFO]    [GUIManager] Registered qglviewer as a GUI.
[INFO]    [GUIManager] Registered qt as a GUI.
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Sofa.GUI.Qt.dll
[DEPRECATED] [SofaValidation] SofaValidation is deprecated. It will be removed at v23.06. For CompareState and CompareTopology, use Sofa.Component.Playback instead.
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaValidation.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SceneCreator.dll
[WARNING] [ObjectFactory] Class already registered: CapsuleCollisionModel<Rigid3d>
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/CollisionOBBCapsule.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/CImgPlugin.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/ArticulatedSystemPlugin.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaEulerianFluid.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaSphFluid.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaDistanceGrid.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaImplicitField.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/MultiThreading.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/DiffusionSolver.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/image_gui.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/image.dll
[WARNING] [PluginManager] Plugin not found in loaded plugins: image
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Registration.dll
[WARNING] [PluginManager] Plugin not found in loaded plugins: Registration
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/InvertibleFVM.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/PluginExample.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/ManifoldTopologies.dll
[WARNING] [PluginManager] Plugin not found in loaded plugins: ManifoldTopologies
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/ManualMapping.dll
[ERROR]   [PluginManager] Plugin not found: "SensableEmulation"
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaCarving.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/Geomagic.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaAssimp.dll
[WARNING] [PluginManager] Plugin not found in loaded plugins: SofaAssimp
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaMatrix.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/BeamAdapter.dll
[INFO]    [PluginManager] Loaded plugin: C:/Program Files/SOFA/v23.06.00/bin/SofaSimpleGUI.dll
[WARNING] [PluginManager] Plugin not found in loaded plugins: SofaSimpleGUI
CUDA error returned from cudaGetDeviceCount: CUDA driver version is insufficient for CUDA runtime version
[ERROR]   [PluginManager] C:/Program Files/SOFA/v23.06.00/bin/SofaCUDA.dll reported an error while trying to initialize. This plugin will not be loaded.
[INFO]    [PluginManager] 85 plugins have been loaded from C:/Program Files/SOFA/v23.06.00/bin/plugin_list.conf
[INFO]    [SofaPluginManager] Loading automatically plugin list in C:/Program Files/SOFA/v23.06.00/config/loadedPlugins.ini
[INFO]    [PluginManager] 0 plugins have been loaded from C:/Program Files/SOFA/v23.06.00/config/loadedPlugins.ini

[INFO]    [SceneCheckerVisitor] Validating node "root" with checks: [SceneCheckCollisionResponse, SceneCheckDeprecatedComponents, SceneCheckDuplicatedName, SceneCheckMissingRequiredPlugin, SceneCheckUsingAlias, SceneCheckMultithreading]
[SUGGESTION] [SceneCheckMultithreading] This scene is using components implemented sequentially while a parallel implementation is available. Using the parallel implementation may improve the performances. Here is the list of sequential components in your scene and their parallel equivalent:
        BVHNarrowPhase -> ParallelBVHNarrowPhase
        BruteForceBroadPhase -> ParallelBruteForceBroadPhase
        HexahedronFEMForceField[Vec3d] -> ParallelHexahedronFEMForceField[Vec3d]

[INFO]    [SceneCheckerVisitor] Finished validating node "root".
[ERROR]   [PluginManager] Plugin loading failed (C:/Program Files/SOFA/v23.06.00/bin/SofaPython3.dll): Das angegebene Modul wurde nicht gefunden.

**Comment by olivier-roussel** [comment]
Have you checked if you have a `SofaPython3.dll` file inside the directory `C:/Program Files/SOFA/v23.06.00/bin` ?

**Comment by wj9991** [comment]
Yes, it is there.

**Comment by olivier-roussel** [comment]
Ok, we miss of verbosity from the SofaPtyhon3 plugin to have more details on the error, but I believe I already saw similar behavior due to an unrecognized python install from SOFA. I don't know if python 3.11 is officially supported on windows for SOFA but 3.8 is normally the way to go, and I have only tested until 3.10 on windows. I don't know neither for a python installed from anaconda / spyder env, I haven't tested that yet. I will try to have a look to diagnose a bit more your error. 
For now, SOFA is only supported with some system-wise requirements (such as requirements on the python version installed on the system). I would recommend you to follow official installation instructions for the binaries for now : https://github.com/sofa-framework/sofa/releases but that would imply to remove your anaconda / spyder installation (which might not be acceptable if you need it for other uses).
Alternatively, if you are familiar with conda, you might have a try on the conda packages, but they are still in development so there are no guarantee. It mainly depends on which SOFA plugins do you plan to use, only few of them are currently packaged in conda.
