### ISSUE TITLE
runSofa crashes when creating a Sofa.Core.Controller object

### ISSUE THREAD

**Issue by psomers3** [sofa-framework/SofaPython3#39]
I've sucessfully compiled the latest sofa with the lastest SofaPython3 without errors on Windows 10 with Visual Studio 16. However, when I try and run the example "ControllerScene.py"  with runSofa it crashes when calling the constructor for the base class in the __init__ function. I've tried just simply creating a default Sofa.Core.Controller() object and it also crashes. Running the script directly with python does work without any problems because it doesn't need to create a Controller.

Am I possibly missing a plugin that the Controller needs?
The only thing I see from the output in terminal is a warning:
` No python dir found in C:/Users/Somers/git/sofa-latest/build/install`

I know the Python3 version is still heavily in development, but is this an issue that could be easily solved? What additional info would be helpful to help figure out the problem?

**Comment by psomers3** [comment]
If it helps, I've narrowed the problem to this point:
It crashes in the py::cast in py_shared_ptr. I believe the problem occurs with the std::forward call that occurs in pybind. When I add the line at 1759 in cast.h
```c++
auto forward_variable = std::forward<T>(value);
```
which is what is passed directly to the cast function, I get the following errors when compiling:

```
C:\Program Files\Python37\Lib\site-packages\pybind11\include\pybind11\cast.h(1759,1): error C2248: 'sofa::core::objectmodel::BaseObject::__vbaseDtor': cannot access protected member declared in class 'sofa::core::objectmodel::BaseObject' (compiling source file C:\Users\Somers\git\sofa-latest\applications\plugins\SofaPython3\bindings\Sofa\src\SofaPython3\Sofa\Core\Binding_BaseObject.cpp)

C:\Program Files\Python37\Lib\site-packages\pybind11\include\pybind11\cast.h(1759,18): error C2259: 'sofa::simulation::Node': cannot instantiate abstract class (compiling source file C:\Users\Somers\git\sofa-latest\applications\plugins\SofaPython3\bindings\Sofa\src\SofaPython3\Sofa\Core\Binding_Node.cpp)

C:\Program Files\Python37\Lib\site-packages\pybind11\include\pybind11\cast.h(1759,1): error C2248: 'sofa::simulation::Node::~Node': cannot access protected member declared in class 'sofa::simulation::Node' (compiling source file C:\Users\Somers\git\sofa-latest\applications\plugins\SofaPython3\bindings\Sofa\src\SofaPython3\Sofa\Core\Binding_Node.cpp)

```

Hope this is helpful. I'll keep digging as I can.

**Comment by jnbrunet** [comment]
Hey @psomers3 ,

Thank you for these hints. We haven't been able to look into it yet, but it should be soon: it is now in our target issues before the first official release of SofaPython3, which should be later this year (December) or at the very beginning (January) of next year.

If you found other hints since August, please let us know !

**Comment by psomers3** [comment]
That's good to hear! I haven't been able to debug it anymore and have since switched to using wsl2 for sofapython3. Would be nice to switch back to a single operating system though.

**Comment by ngvpho** [comment]
Hi SP3 developers,

This image show a finger (orange part on the left side) will make a collision with a fixed cylinder (on right side). 
![Screenshot from 2020-11-23 18-11-32](https://user-images.githubusercontent.com/50490676/99945323-c6a68900-2db7-11eb-9054-0ec4b21db5da.png)
I want to control the orange part by mouse clicking. Do you have any methods or examples about this problem?

Kind regards,
Pho
