### ISSUE TITLE
SimpleApi dependency

### ISSUE THREAD

**Issue by ScheiklP** [sofa-framework/SofaPython3#406]
Hi,
I just tried compiling release `v23.12` of SOFA with release `bakpaul-patch-2` of SP3.

Sadly, cmake throws an error.
```bash
cmake -Wno-dev \
-S $FOLDER_SRC -B $FOLDER_TARGET \
-DCMAKE_BUILD_TYPE=Release \
-DSOFA_FETCH_SOFAPYTHON3=OFF \
-DPLUGIN_SOFAPYTHON3=ON \
-DPython_EXECUTABLE=$PYTHON_EXE \
-DPython_ROOT_DIR=$PYTHON_ROOT_DIR \
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \
-DSP3_BUILD_TEST=OFF \
-DSOFA_BUILD_TESTS=OFF
```

The error complains about not finding `Sofa.SimpleApi`
```
CMake Error at Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake:388 (find_package):
  By not providing "FindSofa.SimpleApi.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Sofa.SimpleApi", but CMake did not find one.

  Could not find a package configuration file provided by "Sofa.SimpleApi"
  with any of the following names:

    Sofa.SimpleApiConfig.cmake
    sofa.simpleapi-config.cmake

  Add the installation prefix of "Sofa.SimpleApi" to CMAKE_PREFIX_PATH or set
  "Sofa.SimpleApi_DIR" to a directory containing one of the above files.  If
  "Sofa.SimpleApi" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  applications/plugins/SofaPython3/bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt:88 (sofa_find_package)
  ```
thrown by [this line](https://github.com/sofa-framework/SofaPython3/blob/1972c51819b6eb5ac1bbc479ff4e29f6f55f36f4/bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt#L88) which was changed in [this commit](https://github.com/sofa-framework/SofaPython3/commit/c063a36d6ed06fc1c43bfeaa2db3689c3d9f2e6f).

Could you help me with that?
Ubuntu 23.10, kernel 6.2.0-39-generic.
cmake version 3.25.1

Cheers,
Paul

**Comment by alxbilger** [comment]
Hi @ScheiklP 

Sofa.SimpleApi is a very recent change in SOFA: https://github.com/sofa-framework/sofa/pull/4495. So your SOFA must be updated in order to use the recent SofaPython3.

Alex

**Comment by ScheiklP** [comment]
Hi @alxbilger ,
ah I see, thanks! :)

Cheers,
Paul
