### ISSUE TITLE
Cannot compile SofaPython3 with python 3.11

### ISSUE THREAD

**Issue by aleblanc30** [sofa-framework/SofaPython3#428]
When compiling Sofa and SofaPython3 from sources on ubuntu 20.04, if python3.11 is installed, SofaPython3 will not compile.

The build fails with the following error : `error: invalid use of incomplete type 'PyFrameObject' {aka 'struct _frame'}`

A quick search online indicated that `PyFrameObject` disappeared in python3.11.

I could not find a cmake parameter to specify which python version to use. I assumed that the system detects the latest version, so I uninstalled python3.11 and compiled the project with python3.10 which solved the issue.

I wrote it down in case further action is needed.

**Comment by bakpaul** [comment]
Hello Alexandre ! 

This looks more like a pybind11 error than a python one. Can you check if the pybind11 lib that is used in your build is the one installed for python3.11 ? You can install pybind11 for your specific python version by calling `python3.11 -m pip install pybind11==2.11.1` (I suggest to use this version, it might not work if you have numpy 2.0, in such case I suggest to use at least 2.12.x). Then make sure that the pybinnd11 lib found by cmake is the one installed for your python version : it should be installed in the dist-package folder of your python version in your personal folder.
