### ISSUE TITLE
Expose my own types to python

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/SofaPython3#56]
In my plugin I have derived a new type from BaseObject.

```
class BlendingField : public sofa::core::objectmodel::BaseObject
{
    virtual double blending(const Eigen::Vector3d &p) const = 0;
}
```
In order to implemente this, I tried to add python bindings

```
class BlendingField : public VNCS::BlendingField
{
public:
    SOFA_CLASS(VNCS::py::BlendingField, VNCS::BlendingField);
    BlendingField();
    ~BlendingField() override;

    VNCS::Real blending(const VNCS::Point_3 &p) const final;
};
...
VNCS::Real VNCS::py::BlendingField::blending(const VNCS::Point_3 &p) const
{
    const std::array<double, 3> pyP{p[0], p[1], p[2]};
    PYBIND11_OVERLOAD_PURE(VNCS::Real,          /* Return type */
                           VNCS::BlendingField, /* Parent class */
                           blending,            /* Name of function in C++ (must match Python name) */
                           pyP                  /* Argument(s) */
    );
}
```

void VNCS::py::module::blendingField(pybind11::module &m)
{
    pybind11::class_<VNCS::BlendingField, VNCS::py::BlendingField>(m, "BlendingField")
        .def(pybind11::init([](pybind11::args &args, pybind11::kwargs &kwargs) {
            return new VNCS::py::BlendingField();
        }))
        .def("blending", &VNCS::BlendingField::blending);
}
This works fine in the sense that I can derive from BlendingField in SOFA, but I can't add it to a SOFA node, with the following error:

```
[ERROR]   [SofaPython3::SceneLoader] TypeError: addObject(): incompatible function arguments. The following argument types are supported:
   1. (self: Sofa.Core.Node, arg0: str, **kwargs) -> object
   2. (self: Sofa.Core.Node, arg0: Sofa.Core.Object) -> object

Invoked with: <Sofa.Core.Node object at 0x7fffac34bef0>, <prepare_scene.TestBlendingField object at 0x7fffac34bea0>
```

Somehow, it looks that SOFA can't see the my class derives from sofa::core::objectmodel::BaseObject. I have tried to find any example of any other plugin creating its own bindings but couldn't find any. 
I added some log output to the ctor and dtor of the BlendingField and it shows that its being destroyed inmediately.
Any help with this would be amazing.

**Comment by jjcasmar** [comment]
Any news on this?

**Comment by jnbrunet** [comment]
Hey @jjcasmar ,

Looks like it is not SOFA that fails, by the python binding function `SofaPython3::sofa::core::Node::addObject`, since it is looking for a Sofa.Core.Object (python binding of BaseObject). I think you have to let pybind11 know that it is inheriting BaseObject, and also let SOFA manage the shared pointer of the created objects:

```c++
void VNCS::py::module::blendingField(pybind11::module &m)
{
    using BaseObject = sofa::core::objectmodel::BaseObject;
    pybind11::class_<VNCS::BlendingField, 
                                BaseObject, 
                                VNCS::py::BlendingField, 
                               sofa::core::sptr<VNCS::BlendingField>>(m, "BlendingField")
    .def(pybind11::init([](pybind11::args &args, pybind11::kwargs &kwargs) {
        return new VNCS::py::BlendingField();
    }))
    .def("blending", &VNCS::BlendingField::blending);
}
```

**Comment by jjcasmar** [comment]
Hi @jnbrunet 
I have tried what you said. Apart from needing `PYBIND11_DECLARE_HOLDER` in my compilation unit for py::BlendingField, it works fine when adding the element into the graph, but fails to call the virtual blending from another Sofa object which references it. 

Basically I have
```    
    const auto &blendingField = *m_blendingFieldLink;
    std::vector<Real> blendingValues;
    blendingValues.reserve(coarsePoints.size());
blendingValues = coarsePoints | ranges::views::transform([&blendingField](const VNCS::SofaTypes::Point &point) {
                         return blendingField.blending({point[0], point[1], point[2]});
                     }) |
                     ranges::to<std::vector>();
```
with `blendingFieldLink` being 

```
    using BlendingFieldLink =
        typename sofa::core::objectmodel::SingleLink<VNCS::SimCreator,
                                                     VNCS::BlendingField,
                                                     sofa::core::objectmodel::BaseLink::FLAG_STOREPATH |
                                                         sofa::core::objectmodel::BaseLink::FLAG_STRONGLINK>;
```

It correctly enters into the `py::BlendingField::blending` call, but throws with the following:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Tried to call pure virtual function "VNCS::BlendingField::blending"
```

Not sure if this is an error of how I am constructing the object or something internal in SOFA. Calling .blending() directly from python works fine 

```
class BlendingField(PyVNCS.BlendingField):
   def __init__(self, *args, **kwargs):
      PyVNCS.BlendingField.__init__(self, *args, **kwargs)
      if "name" in kwargs:
          self.name = kwargs["name"]

   def blending(self, point):
       x = point[0]

       v = 0.0
       if x >= -5 and x <= -2:
           v = 0
       if x > -2 and x <= -1.5:
           v = 2 * x + 4
       if x > -1.5 and x <= 1.5:
           v = 1
       if x > 1.5 and x <= 2:
           v = -2 * x + 4
       if x > 2 and x <= 5:
           v = 0

       return 1 - vp

a = BlendingField()
a.blending([0,0,0])
```

Any idea of what might be happening?

**Comment by jnbrunet** [comment]
Hey @jjcasmar ,

Indeed I forgot about the declaring the holder type.

For your error, can you try:

```c++
PYBIND11_DECLARE_HOLDER_TYPE(VNCS::BlendingField, sofa::core::sptr<VNCS::BlendingField>, true);
PYBIND11_DECLARE_HOLDER_TYPE(VNCS::py::BlendingField, sofa::core::sptr<VNCS::py::BlendingField>, true);

void VNCS::py::module::blendingField(pybind11::module &m)
{
    using BaseObject = sofa::core::objectmodel::BaseObject;

    // Base class
    pybind11::class_<VNCS::BlendingField, 
                     BaseObject, 
                     sofa::core::sptr<VNCS::BlendingField>>(m, "BlendingFieldBase");

    // Trampoline class
    pybind11::class_<VNCS::py::BlendingField, 
                     VNCS::BlendingField,
                     sofa::core::sptr<VNCS::py::BlendingField>>(m, "BlendingField")
    .def(pybind11::init([](pybind11::args &args, pybind11::kwargs &kwargs) {
        return new VNCS::py::BlendingField();
    }))
    .def("blending", &VNCS::BlendingField::blending);
}
```

**Comment by jjcasmar** [comment]
I have tried exactly that but still fails :(

**Comment by jnbrunet** [comment]
Hey @jjcasmar ,

I just saw, you defined your binding of "blending" with

```c++
.def("blending", &VNCS::BlendingField::blending);
```

Where I think it should call your trampoline's one:

```c++
.def("blending", &VNCS::py::BlendingField::blending);
```

**Comment by jjcasmar** [comment]
According to pybind11 docs:
```
py::class_<Animal, PyAnimal /* <--- trampoline*/>(m, "Animal");
    .def(py::init<>())
    .def("go", &PyAnimal::go); /* <--- THIS IS WRONG, use &Animal::go */```

I have tried it anyway and same error

**Comment by jnbrunet** [comment]
Hey @jjcasmar ,

Then I'm sorry, I don't really know how to help you here, this really seems to be coming from pybind11 side. Maybe you can derive a simpler example without SOFA and see if you get the same behavior? You could try seeking help from the pybind11 community, you might have better insight there.

**Comment by jjcasmar** [comment]
Not sure if it coms from pybind11 side. If I try to call the virtual from python side then, work fine

```
BlendingField(PyVNCS::BlendingField):
   def __init__(....
   ...
   def blending(...)
     ...

a = BlendingField()
a.blending([...])
```
but when I add the component to sofa graph, and then try to call the virtual from another component, is when this fails :-s

**Comment by jjcasmar** [comment]
After some research, Ive found that what is happening is that the python object goes out of scope, since the python script finishes, but the object is still being referenced by the C++ side. To temporarily fix this until I find a proper solution, I have added a `keep` method to the binding which basically increases the ref_count of the object. 

```
void VNCS::py::module::blendingField(pybind11::module &m)
{
    pybind11::class_<VNCS::BlendingField, VNCS::py::BlendingField, std::shared_ptr<VNCS::BlendingField>>(
        m, "BlendingField")
        .def(pybind11::init(
            [](pybind11::args &args, pybind11::kwargs &kwargs) { return std::make_shared<VNCS::py::BlendingField>(); }))
        .def("keep", [](pybind11::handle handle) { handle.inc_ref(); });
}
```

With that, it works, although it looks like a terrible hack.
