### ISSUE TITLE
TetrahedronDiffusionFEMForcefield errors on construction in python3

### ISSUE THREAD

**Issue by psomers3** [sofa-framework/SofaPython3#70]
Hi, me again. I'm hoping that I'm doing something wrong, but it seems like there is an issue on construction of the TetrahedronDiffusionFEMForcefield. With the following bare minimum script:

```python
def createScene(rootNode):
    rootNode.addObject('MeshVTKLoader', name='meshLoader', filename='mesh/raptorTetra_8418.vtu')
    rootNode.addObject('MeshObjLoader', name='potentialLoader', filename='mesh/raptorTemperature.obj')
    rootNode.addObject('MechanicalObject', name='tetradofs', template='Vec3d')
    rootNode.addObject('TetrahedronSetTopologyContainer', src='@meshLoader', name='asdf')
    temperatures = Sofa.Components.MechanicalObject(rootNode, template='Vec1d', name='gridTemperature', position='@potentialLoader.position', tags='heat')
    diffusion = Sofa.Components.TetrahedronDiffusionFEMForceField(rootNode,
                                                                  template='Vec1d',
                                                                  topology='@asdf',
                                                                  name='DiffusionForceField',
                                                                  constantDiffusionCoefficient=1500,
                                                                  tagMechanics="mechanics")
```

I always get the error:
`
[ERROR]   [TetrahedronDiffusionFEMForceField(TetrahedronDiffusionFEMForceField)] cannot find the mechanical object named '0  
`
Seems like the wrong value for the name of the mechanical state is getting passed somewhere?

**Comment by jnbrunet** [comment]
Hey @psomers3 ,

Sorry for the delay. Did you managed to solve your issue?

**Comment by psomers3** [comment]
Hey! Thanks for the answer, I know you guys have been retardedly busy in the last weeks (super happy to see the fixes to my other issue).
I actually just this morning have run into the same problem in pure c++ use of sofa, so it is **not** a python issue. I'm guessing I'm just not understanding the tags well enough for the TetrahedronDiffusionFEM. The example scene works using runSofa... so I guess I need to see if I can emulate that. If I can't, I'll try and upload a barebones example of the c++ code I'm working with.

**Comment by jnbrunet** [comment]
Hey @psomers3 ,

Interesting.  I never used this component, however a quick look at its implementation shows that it is looking for a mechanical object having the same tag as the one defined by the `tagMechanics` attribute. In your scene, it looks like the tag of the Forcfield is **mechanics** while the one of the mechanical object is **heat**. Could this be the issue?

In any cases, don't hesitate to post this on the forum, you might have better chances that someone already bump into this issue.

I will close this issue here since it isn't related to SofaPython3.

Good luck and thanks again for reporting the issues you are facing.

**Comment by psomers3** [comment]
Going off the example scene from sofa it needs 2 mechanical objects, one tagged "mechanical" for the topology I guess(?) and one tagged "heat". The latter holding the DOFs of the temperature. In my posted example, I'm missing some tags and apparently it also needs a TetrahedronSetGeometryAlgorithms. Working:

```python
def createScene(rootNode):
    rootNode.addObject('MeshVTKLoader', name='meshLoader', filename='mesh/raptorTetra_8418.vtu')
    rootNode.addObject('MeshObjLoader', name='potentialLoader', filename='mesh/raptorTemperature.obj')
    rootNode.addObject('MechanicalObject', name='tetradofs', src="@meshLoader", template='Vec3d', tags="mechanics")
    rootNode.addObject('TetrahedronSetGeometryAlgorithms', name="GeoAlgo", tags="mechanics")
    rootNode.addObject('TetrahedronSetTopologyContainer', src='@meshLoader', name='asdf')
    temperatures = Sofa.Components.MechanicalObject(rootNode, template='Vec1d', name='gridTemperature', position='@potentialLoader.position', tags='heat')
    diffusion = Sofa.Components.TetrahedronDiffusionFEMForceField(rootNode,
                                                                  template='Vec1d',
                                                                  topology='@asdf',
                                                                  name='DiffusionForceField',
                                                                  constantDiffusionCoefficient=1500,
                                                                  tagMechanics="mechanics",
                                                                  tags="heat")
```

Thanks again for the help!!
