### ISSUE TITLE
Add bindings for sofa::component::interactionforcefield::LinearSpring

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/SofaPython3#77]
This issue was raised by @ScheiklP (see [here](https://www.sofa-framework.org/community/forum/topic/deleting-springs-via-sofapython3/)).

The data field `SpringForceField::springs` has the following type:
```c++
sofa::helper::vector<sofa::component::interactionforcefield::LinearSpring<Real>>
```

Since the class `sofa::component::interactionforcefield::LinearSpring` hasn't been bound to python, getting the datafield in python returns a vector of empty entries (the shape of the vector is good since `sofa::helper::vector` has been bound to python).

To fix it, we need to add bindings for `sofa::component::interactionforcefield::LinearSpring<Real>`.  These will need to be added in a new binding library. Following what we have done for `SofaBaseTopology`, the following steps would be needed:
1. Add a new CMake project `Bindings.Modules.SofaDeformable` in _bindings/Modules/src/SofaPython3/SofaDeformable_ 
2. In this project, create a new python module `SofaDeformable` and link it against the SOFA target `SofaDeformable`
3. Add bindings for the classes: 
    1. `sofa::component::interactionforcefield::SpringForceField`, especially the methods `addSpring` and `removeSpring`
    2. `sofa::component::interactionforcefield::LinearSpring`
4. Add unittests for these new bindings (we can base the tests on [the following scene](https://cloud.ipr.kit.edu/s/STwn3oAHNn4dnnG) provided by @ScheiklP)

**Comment by ScheiklP** [comment]
I tried something here: https://github.com/ScheiklP/SofaPython3/commit/c436e7c2fbc4c9d954aca2e0dda0c05f5693fc22
I would love to support you on this so I can learn how to do that properly.

That should make future contributions a bit easier. :D

**Comment by jnbrunet** [comment]
Hey @ScheiklP ,

Thanks a lot for this ! We get a lot of request, but not that much contributions, so it is **very** appreciated. Could you create a PR with the label "status: WIP"? It will be easier to follow the development of this new feature.

After a very quick look, the proposed changes look exactly as I would have done it.

**Comment by ScheiklP** [comment]
Hi @jnbrunet ,
you are very welcome! :)
I think SOFA and SP3 are very important projects for the community.

Of course, will do!
The code currently does not build because of a "x not known in this context"-error from a boost datatype.
Sadly I know too little about how boost is integrated into SOFA to pinpoint the location of that problem.

**Comment by ScheiklP** [comment]
> This issue was raised by @ScheiklP (see [here](https://www.sofa-framework.org/community/forum/topic/deleting-springs-via-sofapython3/)).
> 
> The data field `SpringForceField::springs` has the following type:
> 
> ```c++
> sofa::helper::vector<sofa::component::interactionforcefield::LinearSpring<Real>>
> ```
> 
> Since the class `sofa::component::interactionforcefield::LinearSpring` hasn't been bound to python, getting the datafield in python returns a vector of empty entries (the shape of the vector is good since `sofa::helper::vector` has been bound to python).
> 
> To fix it, we need to add bindings for `sofa::component::interactionforcefield::LinearSpring<Real>`. These will need to be added in a new binding library. Following what we have done for `SofaBaseTopology`, the following steps would be needed:
> 
> 1. Add a new CMake project `Bindings.Modules.SofaDeformable` in _bindings/Modules/src/SofaPython3/SofaDeformable_
> 2. In this project, create a new python module `SofaDeformable` and link it against the SOFA target `SofaDeformable`
> 3. Add bindings for the classes:
>    
>    1. `sofa::component::interactionforcefield::SpringForceField`, especially the methods `addSpring` and `removeSpring`
>    2. `sofa::component::interactionforcefield::LinearSpring`
> 4. Add unittests for these new bindings (we can base the tests on [the following scene](https://cloud.ipr.kit.edu/s/STwn3oAHNn4dnnG) provided by @ScheiklP)

Thanks a lot for that explanation! I did not realize, that that was a smart pointer thing. :)
